apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: k0smotron
  labels:
    k0smotron-provider: infrastructure
spec:
  selector:
    matchLabels:
      k0smotron-provider: infrastructure
  template:
    metadata:
      labels:
        k0smotron-provider: infrastructure
    spec:
      containers:
      - name: manager
