# options for analysis running
run:
  timeout: 8m

  build-tags:
    - hack
  skip-dirs-use-default: false
  skip-files:
    - "zz_*"
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - depguard     # Checks if package imports are in a list of acceptable packages
    - gofmt        # Checks whether code was gofmt-ed
    - goheader     # Checks is file headers matche a given pattern
    - revive       # Stricter drop-in replacement for golint
    - ginkgolinter # Enforces standards of using ginkgo and gomega
