# permissions for end users to edit k0smotronclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: k0smotroncluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k0smotron
    app.kubernetes.io/part-of: k0smotron
    app.kubernetes.io/managed-by: kustomize
  name: k0smotroncluster-editor-role
rules:
- apiGroups:
  - k0smotron.io
  resources:
  - k0smotronclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k0smotron.io
  resources:
  - k0smotronclusters/status
  verbs:
  - get
- apiGroups:
  - exp.cluster.x-k8s.io
  - cluster.x-k8s.io
  resources:
  - machinepools
  - machinepools/status
  verbs:
  - get
  - list
  - watch
