apiVersion: v1
kind: Pod
metadata:
  name: webhook-checker
  namespace: k0smotron
spec:
  containers:
    - image: curlimages/curl:8.10.1
      name: webhook-checker
      command:
        - sh
        - -c
        - "sleep 360"
      readinessProbe:
        exec:
          command:
            - sh
            - -c
            - "curl -k https://k0smotron-webhook-service/mutate-k0smotron-io-v1beta1-cluster"
        periodSeconds: 5